version: '3.8'

services:
  # 1. Backend Python
  backend:
    build: ./backend
    container_name: dreamjob_backend
    restart: always
    ports:
      - "8000:8000" # Mở port này để test hoặc để Nginx gọi

  # 2. Frontend Next.js
  frontend:
    build: ./frontend
    container_name: dreamjob_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Khi build docker, Frontend gọi Backend qua tên service 'backend'
      NEXT_PUBLIC_API_URL: https://tool.dreamjob.blog/api/v1 

  # 3. Nginx (Cổng chính - Đón khách)
  nginx:
    image: nginx:alpine
    container_name: dreamjob_nginx
    restart: always
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - frontend
      - backend